filebeat.inputs:
  - type: filestream
    id: vcs-sms
    paths:
      - /var/log/app/*.log
    parsers:
    - ndjson:
        keys_under_root: true
        overwrite_keys: true
        add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]

