// Code generated by MockGen. DO NOT EDIT.
// Source: ./auth_middleware.go
//
// Generated by this command:
//
//	mockgen -source ./auth_middleware.go -destination ./mock_auth_middleware.go
//

// Package mock_middleware is a generated GoMock package.
package middleware

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthMiddleware is a mock of AuthMiddleware interface.
type MockAuthMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMiddlewareMockRecorder
	isgomock struct{}
}

// MockAuthMiddlewareMockRecorder is the mock recorder for MockAuthMiddleware.
type MockAuthMiddlewareMockRecorder struct {
	mock *MockAuthMiddleware
}

// NewMockAuthMiddleware creates a new mock instance.
func NewMockAuthMiddleware(ctrl *gomock.Controller) *MockAuthMiddleware {
	mock := &MockAuthMiddleware{ctrl: ctrl}
	mock.recorder = &MockAuthMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthMiddleware) EXPECT() *MockAuthMiddlewareMockRecorder {
	return m.recorder
}

// CheckUserPermission mocks base method.
func (m *MockAuthMiddleware) CheckUserPermission(requiredScope string) gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserPermission", requiredScope)
	ret0, _ := ret[0].(gin.HandlerFunc)
	return ret0
}

// CheckUserPermission indicates an expected call of CheckUserPermission.
func (mr *MockAuthMiddlewareMockRecorder) CheckUserPermission(requiredScope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserPermission", reflect.TypeOf((*MockAuthMiddleware)(nil).CheckUserPermission), requiredScope)
}
